import { CEO_EMAIL, CEO_PASSWORD } from '@/lib/auth/ceo';

export const SEED_HEROES = [
  {
    id: 'h1',
    type: 'image',
    src: '/hero/savanna.jpg',
    palette: { from: '#5e2a0a', via: '#a85820', to: '#f4c46b' },
    accent: '#d4af37',
    subject: 'lion',
    title: 'Pride of the Savanna',
    description:
      'Where golden grasslands stretch beyond the horizon, the lion’s gaze defines the wild.',
    cta: { label: 'Explore', href: '/animals/mammals' },
    createdAt: '2026-04-19T00:00:00.000Z',
  },
  {
    id: 'h2',
    type: 'image',
    src: '/hero/canopy.jpg',
    palette: { from: '#031a0d', via: '#0c4a1a', to: '#3aa15a' },
    accent: '#d4af37',
    subject: 'forest',
    title: 'The Living Canopy',
    description:
      'Beneath endless emerald layers, an entire universe breathes, hunts, and grows in silence.',
    cta: { label: 'Explore', href: '/plants/trees' },
    createdAt: '2026-04-19T00:00:00.000Z',
  },
  {
    id: 'h3',
    type: 'image',
    src: '/hero/eagle.jpg',
    palette: { from: '#0a1a3a', via: '#1f4a8a', to: '#a8d0f5' },
    accent: '#d4af37',
    subject: 'eagle',
    title: 'Sovereign Skies',
    description:
      'High above mountain ridges, the raptor commands every current of wind and light.',
    cta: { label: 'Explore', href: '/birds/raptors' },
    createdAt: '2026-04-19T00:00:00.000Z',
  },
];

export const SEED_POSTS = [
  {
    id: 'p1',
    slug: 'snow-leopards-himalaya',
    title: 'The Last of the Snow Leopards',
    description:
      'High in the Himalayas, an elusive predator clings to its disappearing world.',
    body:
      'For centuries the snow leopard has hunted in silence among the highest peaks of Central Asia. Today, fewer than 6,000 remain in the wild — a number shrinking each year as human settlement creeps higher and prey populations dwindle.\n\nResearchers tracking these ghosts of the mountains rely on motion-triggered cameras hidden in passes between 3,000 and 5,500 meters. The images they capture show animals so perfectly adapted to the alpine cold that they almost vanish into the snow.\n\nConservation efforts now span twelve countries, but the species\' fate may ultimately rest on something far more fragile: a single warming degree, a single lost generation of bharal sheep, a single highway through the wrong valley.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#0a1a3a', via: '#3a5a7a', to: '#c8d8e8' },
    featured: true,
    createdAt: '2026-04-15T00:00:00.000Z',
    authorId: 'u_ceo',
  },
  {
    id: 'p2',
    slug: 'living-canopy-secrets',
    title: 'Secrets of the Living Canopy',
    description:
      'Beneath endless emerald layers, an entire universe breathes, hunts, and grows in silence.',
    body:
      'A single hectare of mature rainforest canopy can host more species than the entire continent of Europe. From orchid-dwelling mites no larger than a comma to harpy eagles ruling the upper terraces, the vertical city of the trees runs on rules we are only beginning to understand.\n\nNew survey techniques — laser scanning, environmental DNA, and acoustic monitoring — are revealing patterns of life that traditional fieldwork could never capture. Entire choruses of insect species rise and fall on hourly cycles. Sap flow synchronizes across thousands of trees.\n\nThe canopy is not a backdrop for biodiversity. It IS biodiversity, organized in three dimensions.',
    category: 'plants',
    label: 'Trees',
    cover: null,
    coverPalette: { from: '#031a0d', via: '#0c4a1a', to: '#3aa15a' },
    featured: true,
    createdAt: '2026-04-12T00:00:00.000Z',
    authorId: 'u_ceo',
  },
  {
    id: 'p3',
    slug: 'sovereign-skies-raptors',
    title: 'Sovereign Skies: The Raptor Renaissance',
    description:
      'After decades of decline, peregrines, eagles, and ospreys are reclaiming continents one updraft at a time.',
    body:
      'The peregrine falcon was functionally extinct east of the Rocky Mountains by 1970. The bald eagle nearly followed. Today both species are not just recovering — they are colonizing skylines that didn\'t exist when their populations crashed.\n\nUrban raptor density now rivals the most pristine wilderness in some North American cities. Pigeons and rats provide the prey base; office towers replace the cliff faces. The birds adapted to us before we figured out how to coexist with them.\n\nThis is one of conservation\'s genuine success stories — built on a single piece of legislation, a continent-wide ban on a single chemical, and the patience of ornithologists who refused to give up.',
    category: 'birds',
    label: 'Raptors',
    cover: null,
    coverPalette: { from: '#1a0a05', via: '#5a3520', to: '#e8a060' },
    featured: true,
    createdAt: '2026-04-10T00:00:00.000Z',
    authorId: 'u_ceo',
  },
  {
    id: 'p4',
    slug: 'glass-frogs-vanishing',
    title: 'Glass Frogs and the Art of Vanishing',
    description:
      'Translucent skin, silent leaps — the camouflage strategy of a forgotten amphibian.',
    body:
      'Through the underside of a glass frog, you can see its beating heart. The species has evolved a kind of biological invisibility: when at rest on a leaf, ambient light passes through the body and renders the silhouette nearly indistinguishable from the foliage.\n\nResearchers recently discovered that the frogs achieve this trick by sequestering nearly all of their red blood cells into the liver while sleeping — temporarily reducing the visible reddish hue that would otherwise give them away.\n\nIt is one of the most elegant survival strategies on record, and it was hiding in plain sight for centuries.',
    category: 'animals',
    label: 'Amphibians',
    cover: null,
    coverPalette: { from: '#0a2a14', via: '#2a8a4a', to: '#a8e0c0' },
    featured: false,
    createdAt: '2026-04-05T00:00:00.000Z',
    authorId: 'u_ceo',
  },
  {
    id: 'p5',
    slug: 'african-lion-pride',
    title: 'African Lion',
    description: 'Apex predator of the savanna — the mane-crowned king whose roar carries five miles across open grassland.',
    body: 'The African lion is the only truly social big cat, living in prides of up to 30 individuals across sub-Saharan savannas and open woodlands. Lions sleep up to 20 hours a day, conserving energy for explosive hunts that can reach 80 km/h in short bursts.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#3a1500', via: '#a05808', to: '#f0c030' },
    featured: true,
    createdAt: '2026-04-20T06:00:00.000Z',
    authorId: 'u_ceo',
    views: 142,
  },
  {
    id: 'p6',
    slug: 'african-elephant',
    title: 'African Elephant',
    description: 'The largest land animal on Earth — a matriarch-led society that reshapes entire landscapes.',
    body: 'African elephants use infrasound to communicate across kilometres, mourn their dead, and demonstrate tool use. A single herd can consume 300 kg of vegetation daily, making them keystone engineers of the savanna ecosystem.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#1a140c', via: '#5a4a38', to: '#a89070' },
    featured: false,
    createdAt: '2026-04-19T10:00:00.000Z',
    authorId: 'u_ceo',
    views: 98,
  },
  {
    id: 'p7',
    slug: 'mountain-gorilla',
    title: 'Mountain Gorilla',
    description: 'Deep in volcanic mist — a silverback intelligence that shares 98% of our DNA.',
    body: 'Fewer than 1,100 mountain gorillas remain, making them one of the most critically endangered great apes. Found only in the Albertine Rift\'s montane forests, they live in stable family groups led by a dominant silverback who can weigh over 200 kg.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#080e06', via: '#183810', to: '#446840' },
    featured: false,
    createdAt: '2026-04-18T08:00:00.000Z',
    authorId: 'u_ceo',
    views: 76,
  },
  {
    id: 'p8',
    slug: 'nile-crocodile',
    title: 'Nile Crocodile',
    description: 'Ancient and armoured — a 200 million-year-old design that still rules Africa\'s rivers.',
    body: 'Nile crocodiles are the largest freshwater predators in Africa, reaching 6 metres and 750 kg. They are remarkably attentive parents: females guard nests for three months and carry hatchlings to water in their mouths, one of the most tender moments in reptile behaviour.',
    category: 'animals',
    label: 'Reptiles',
    cover: null,
    coverPalette: { from: '#101600', via: '#384416', to: '#708448' },
    featured: false,
    createdAt: '2026-04-17T14:00:00.000Z',
    authorId: 'u_ceo',
    views: 54,
  },
  {
    id: 'p9',
    slug: 'cheetah-velocity',
    title: 'Cheetah',
    description: 'Zero to 112 km/h in three seconds — evolution\'s most refined speed machine.',
    body: 'The cheetah is the fastest land animal alive, built around a flexible spine that acts as a spring, doubling stride length. Unlike other big cats, cheetahs cannot roar — they purr, chirp, and yelp. Their spotted coats are as unique as fingerprints.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#281400', via: '#785010', to: '#d8a838' },
    featured: false,
    createdAt: '2026-04-16T09:00:00.000Z',
    authorId: 'u_ceo',
    views: 88,
  },
  {
    id: 'p10',
    slug: 'king-cobra',
    title: 'King Cobra',
    description: 'The longest venomous snake on Earth — rearing tall enough to look a human in the eye.',
    body: 'King cobras can reach 5.5 metres and are unique among snakes in building nests and guarding their eggs. Contrary to myth, they prefer to avoid confrontation, eating primarily other snakes. Their venom is powerful enough to kill an elephant.',
    category: 'animals',
    label: 'Reptiles',
    cover: null,
    coverPalette: { from: '#060e00', via: '#1c4406', to: '#508018' },
    featured: false,
    createdAt: '2026-04-14T11:00:00.000Z',
    authorId: 'u_ceo',
    views: 63,
  },
  {
    id: 'p11',
    slug: 'humpback-whale',
    title: 'Humpback Whale',
    description: 'Oceans\' greatest singers — 50-tonne composers performing songs that evolve across hemispheres.',
    body: 'Humpback whale songs can last for hours and travel thousands of kilometres underwater. All male humpbacks in a population sing the same song, which shifts slowly over months — a cultural transmission unique among non-human animals. They migrate up to 25,000 km annually.',
    category: 'animals',
    label: 'Mammals',
    cover: null,
    coverPalette: { from: '#041428', via: '#0c3868', to: '#3080c0' },
    featured: false,
    createdAt: '2026-04-13T07:00:00.000Z',
    authorId: 'u_ceo',
    views: 110,
  },

  /* ── "Posts" category (trending articles) ─────────────── */
  {
    id: 'p12',
    slug: 'why-lions-are-kings-savanna',
    title: 'Why Lions Are the True Kings of the Savanna',
    description: 'Beyond the mane and the roar — the behavioural science that makes the lion the defining apex predator of sub-Saharan Africa.',
    body: 'The lion\'s dominance over the African savanna is not simply a matter of brute force. It is a story of coalition, intelligence, and territorial mastery refined over two million years of evolution. Pride dynamics, coordinated nocturnal hunts, and infrasonic communication give lions a social sophistication unmatched by any other cat.',
    category: 'posts',
    label: 'Why',
    cover: null,
    coverPalette: { from: '#2a1000', via: '#8a4800', to: '#c89030' },
    featured: true,
    createdAt: '2026-04-21T08:00:00.000Z',
    authorId: 'u_ceo',
    views: 2840,
  },
  {
    id: 'p13',
    slug: 'perfect-wildlife-safari-2026',
    title: 'How to Plan the Perfect Wildlife Safari in 2026',
    description: 'A complete field guide — from choosing the right ecosystem to booking the right camp, timing the migration, and packing smart.',
    body: 'Planning a safari is as much a science as it is an art. The difference between a life-changing experience and a missed opportunity often comes down to three decisions: where you go, when you go, and who guides you there. This guide covers all three in depth.',
    category: 'posts',
    label: 'How',
    cover: null,
    coverPalette: { from: '#0a1a08', via: '#1a4810', to: '#50905a' },
    featured: false,
    createdAt: '2026-04-20T14:00:00.000Z',
    authorId: 'u_ceo',
    views: 2120,
  },
  {
    id: 'p14',
    slug: 'tanzania-tourism-safari-boom',
    title: "Tanzania Tourism: Africa's Fastest-Growing Safari Destination",
    description: 'How the Serengeti, Ngorongoro, and Zanzibar together created a $3.5 billion wildlife economy — and what it means for conservation.',
    body: 'Tanzania\'s tourism industry has grown at 12% annually for five consecutive years, largely driven by wildlife-focused travel. The paradox at the heart of this boom is fascinating: the more tourists arrive, the greater the pressure on ecosystems — yet the greater the funding for their protection.',
    category: 'posts',
    label: 'Tourism',
    cover: null,
    coverPalette: { from: '#1a0a00', via: '#6a3010', to: '#c07030' },
    featured: false,
    createdAt: '2026-04-19T11:00:00.000Z',
    authorId: 'u_ceo',
    views: 1870,
  },
  {
    id: 'p15',
    slug: 'mountain-gorilla-conservation-victory',
    title: 'Conservation Victory: How We Brought Mountain Gorillas Back',
    description: 'From 620 individuals in 1989 to over 1,100 today — the remarkable, multi-nation effort that reversed the gorilla\'s extinction trajectory.',
    body: 'The mountain gorilla recovery stands as one of conservation\'s most instructive case studies. It required a precise alignment of political will across three countries, community engagement at the village level, and a tourism model that made living gorillas more valuable than dead ones.',
    category: 'posts',
    label: 'Conservation',
    cover: null,
    coverPalette: { from: '#080e06', via: '#163014', to: '#3a6030' },
    featured: false,
    createdAt: '2026-04-18T16:00:00.000Z',
    authorId: 'u_ceo',
    views: 1540,
  },
  {
    id: 'p16',
    slug: 'wildlife-documentaries-must-watch',
    title: '10 Wildlife Documentaries That Changed How We See Nature',
    description: 'From Planet Earth to My Octopus Teacher — the films that rewired public understanding of the natural world and catalysed real policy change.',
    body: 'The relationship between documentary filmmaking and conservation policy is more direct than most people realise. Attenborough\'s Blue Planet II directly triggered legislative bans on single-use plastics in five countries within 18 months of broadcast. This is the power — and the responsibility — of the nature documentary.',
    category: 'posts',
    label: 'Articles',
    cover: null,
    coverPalette: { from: '#0a0a1a', via: '#1c1c3a', to: '#484880' },
    featured: false,
    createdAt: '2026-04-17T09:00:00.000Z',
    authorId: 'u_ceo',
    views: 1320,
  },

  /* ── Plants species ─────────────────────────────────────── */
  {
    id: 'p17',
    slug: 'baobab-tree-of-life',
    title: 'Baobab — The Tree of Life',
    description: 'Africa\'s most iconic silhouette: a tree that stores thousands of litres of water inside its vast trunk and lives for thousands of years.',
    body: 'The baobab stores up to 120,000 litres of water in its swollen trunk — a survival strategy refined over millennia of African drought. Some individuals are over 2,500 years old, making them living monuments to ancient ecosystems. Eight species exist, six found only in Madagascar.',
    category: 'plants',
    label: 'Trees',
    cover: null,
    coverPalette: { from: '#2a1400', via: '#7a4010', to: '#c89040' },
    featured: true,
    createdAt: '2026-04-21T07:00:00.000Z',
    authorId: 'u_ceo',
    views: 940,
  },
  {
    id: 'p18',
    slug: 'venus-flytrap-carnivore',
    title: 'Venus Flytrap',
    description: 'Nature\'s most theatrical predator — a plant that counts, remembers, and snaps shut in under 100 milliseconds.',
    body: 'The Venus flytrap is native only to a 100-mile radius around Wilmington, North Carolina. Its traps close only when the inner trigger hairs are touched twice within 20 seconds — a counting mechanism that prevents wasted energy on raindrops. It digests insects over 5–12 days.',
    category: 'plants',
    label: 'Carnivorous',
    cover: null,
    coverPalette: { from: '#0c1a00', via: '#3a2010', to: '#804020' },
    featured: false,
    createdAt: '2026-04-20T09:00:00.000Z',
    authorId: 'u_ceo',
    views: 820,
  },
  {
    id: 'p19',
    slug: 'giant-sequoia-forest',
    title: 'Giant Sequoia',
    description: 'The largest living organism by volume on Earth — a titan of the Sierra Nevada that has survived ice ages, wildfires, and centuries of human pressure.',
    body: 'General Sherman, the largest known giant sequoia, contains enough wood to build 40 five-room houses. These trees live over 3,000 years and are remarkably fire-resistant, with bark up to 60 cm thick. Their cones stay closed for 20 years, releasing seeds only when opened by fire.',
    category: 'plants',
    label: 'Trees',
    cover: null,
    coverPalette: { from: '#0a1408', via: '#2a4018', to: '#6a8040' },
    featured: false,
    createdAt: '2026-04-19T13:00:00.000Z',
    authorId: 'u_ceo',
    views: 760,
  },
  {
    id: 'p20',
    slug: 'blue-lotus-sacred-water-lily',
    title: 'Blue Lotus',
    description: 'Sacred to ancient Egypt for 3,000 years — the flower of divine rebirth that blooms at dawn and retreats beneath the water at dusk.',
    body: 'Nymphaea caerulea, the blue lotus, was central to Egyptian ritual, art, and medicine. It contains nuciferine and aporphine — compounds with mild psychoactive properties that ancient Egyptians may have used in religious ceremonies. It opens precisely at sunrise and closes at sunset, symbolising the eternal cycle of Ra.',
    category: 'plants',
    label: 'Aquatic',
    cover: null,
    coverPalette: { from: '#040c1a', via: '#0c2050', to: '#6040a0' },
    featured: false,
    createdAt: '2026-04-18T11:00:00.000Z',
    authorId: 'u_ceo',
    views: 680,
  },
  {
    id: 'p21',
    slug: 'titan-arum-corpse-flower',
    title: 'Titan Arum — The Corpse Flower',
    description: 'The largest unbranched inflorescence on Earth blooms for 48 hours, smells of rotting flesh, and can be heard heating itself from metres away.',
    body: 'Amorphophallus titanum generates its own heat through a process called thermogenesis, reaching temperatures 10°C above ambient to volatilise sulphur compounds that mimic decomposing meat. A single bloom can reach 3 metres tall. It flowers unpredictably — sometimes once every 7–10 years — attracting crows of thousands of visitors when it does.',
    category: 'plants',
    label: 'Rare',
    cover: null,
    coverPalette: { from: '#100814', via: '#2a1030', to: '#602050' },
    featured: false,
    createdAt: '2026-04-17T15:00:00.000Z',
    authorId: 'u_ceo',
    views: 1140,
  },
  {
    id: 'p22',
    slug: 'rafflesia-arnoldii-giant-bloom',
    title: 'Rafflesia arnoldii',
    description: 'The world\'s largest individual flower — a parasitic bloom with no leaves, roots, or stem that emerges straight from its host vine.',
    body: 'Rafflesia arnoldii produces flowers up to 106 cm in diameter and weighing 11 kg. It is entirely parasitic, with no chlorophyll, existing only as thread-like filaments inside the tissues of Tetrastigma vines until its flower bud bursts through. Found only in the rainforests of Sumatra and Borneo, it is critically threatened by deforestation.',
    category: 'plants',
    label: 'Parasitic',
    cover: null,
    coverPalette: { from: '#1a0404', via: '#5a1010', to: '#a03020' },
    featured: false,
    createdAt: '2026-04-16T12:00:00.000Z',
    authorId: 'u_ceo',
    views: 870,
  },
  {
    id: 'p23',
    slug: 'dragon-blood-tree-socotra',
    title: 'Dragon Blood Tree',
    description: 'From an island so isolated it evolved alone — the umbrella-shaped tree that bleeds crimson resin and has survived 20 million years of isolation.',
    body: 'Dracaena cinnabari grows only on Socotra Island, a UNESCO World Heritage site so isolated it has been called "the Galapagos of the Indian Ocean." Its inverted umbrella crown is designed to maximise moisture capture from coastal fog. Its dark red sap — dragon\'s blood — has been used as medicine, varnish, and dye for millennia.',
    category: 'plants',
    label: 'Endemic',
    cover: null,
    coverPalette: { from: '#140408', via: '#400c18', to: '#802840' },
    featured: false,
    createdAt: '2026-04-15T10:00:00.000Z',
    authorId: 'u_ceo',
    views: 720,
  },
  {
    id: 'p24',
    slug: 'mangrove-coastal-forests',
    title: 'Mangrove Forests',
    description: 'Saltwater architects — the tangled, oxygen-rich forests at the edge of land and sea that shelter 40% of all marine fish in their juvenile phase.',
    body: 'Mangrove forests occupy just 0.1% of Earth\'s surface but store up to 10 times more carbon per hectare than terrestrial forests. Their prop roots create nurseries for fish, filter coastal water, and provide a buffer that reduces tsunami impact by up to 90%. They are disappearing at four times the rate of tropical rainforest.',
    category: 'plants',
    label: 'Ecosystems',
    cover: null,
    coverPalette: { from: '#041410', via: '#0c3428', to: '#3a7060' },
    featured: false,
    createdAt: '2026-04-14T08:00:00.000Z',
    authorId: 'u_ceo',
    views: 590,
  },

  /* ── IUCN Red List Species ─────────────────────────────── */

  /* EX — Extinct */
  {
    id: 'p25',
    slug: 'thylacine-tasmanian-tiger-extinct',
    title: 'Thylacine',
    description: 'The last known individual died in Hobart Zoo on 7 September 1936 — extinction of a predator that had endured four million years of evolution.',
    body: 'The thylacine, or Tasmanian tiger, was the largest known carnivorous marsupial of modern times. Systematic hunting driven by colonial bounty systems from 1830 to 1909 reduced its population from thousands to zero in under a century. Its striped hindquarters and wolf-like gait made it unique among marsupials.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EX',
    cover: null,
    coverPalette: { from: '#080808', via: '#282828', to: '#4a4a4a' },
    featured: false,
    createdAt: '2026-04-21T05:50:00.000Z',
    authorId: 'u_ceo',
    views: 740,
  },
  {
    id: 'p26',
    slug: 'dodo-raphus-cucullatus',
    title: 'Dodo',
    description: 'Vanished from Mauritius around 1693 — less than 80 years after European contact. A permanent symbol of human-caused extinction.',
    body: 'Raphus cucullatus was a flightless bird endemic to Mauritius that had evolved without mammalian predators, rendering it completely unafraid of humans. Within 80 years of Portuguese sailors arriving in 1598, hunting and introduced rats erased a species that had endured for millennia.',
    category: 'birds',
    label: 'Flightless',
    iucnStatus: 'EX',
    cover: null,
    coverPalette: { from: '#0c0c0c', via: '#303028', to: '#585848' },
    featured: false,
    createdAt: '2026-04-21T05:40:00.000Z',
    authorId: 'u_ceo',
    views: 820,
  },
  {
    id: 'p27',
    slug: 'passenger-pigeon-extinct',
    title: 'Passenger Pigeon',
    description: 'Once numbering three to five billion — the most abundant bird in North America. The last individual, Martha, died in captivity in 1914.',
    body: 'The passenger pigeon formed flocks so enormous they darkened the sky for days. Industrial-scale hunting for meat markets, combined with deforestation, collapsed the entire species from billions to zero in under 50 years. Martha, the last known individual, died in Cincinnati Zoo on 1 September 1914.',
    category: 'birds',
    label: 'Extinct',
    iucnStatus: 'EX',
    cover: null,
    coverPalette: { from: '#101018', via: '#282838', to: '#484870' },
    featured: false,
    createdAt: '2026-04-21T05:30:00.000Z',
    authorId: 'u_ceo',
    views: 580,
  },

  /* EW — Extinct in the Wild */
  {
    id: 'p28',
    slug: 'scimitar-horned-oryx-extinct-wild',
    title: 'Scimitar-horned Oryx',
    description: 'Declared extinct in the wild in 2000 — but international reintroduction has returned hundreds to Tunisia and Chad since 2016.',
    body: 'Oryx dammah once ranged across the entire Sahara-Sahel belt in herds of thousands. Unregulated hunting and severe drought drove it to extinction in the wild by 2000. Coordinated reintroduction since 2016 has returned hundreds to protected reserves in Tunisia and a Chadian population now numbering in the thousands.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EW',
    cover: null,
    coverPalette: { from: '#10041a', via: '#2c1050', to: '#5a2888' },
    featured: false,
    createdAt: '2026-04-21T05:20:00.000Z',
    authorId: 'u_ceo',
    views: 410,
  },
  {
    id: 'p29',
    slug: 'wyoming-toad-extinct-wild',
    title: 'Wyoming Toad',
    description: 'Last collected from the wild in 1983 — now survives only through an intensive captive breeding and annual release programme.',
    body: 'Anaxyrus baxteri was once abundant in Wyoming\'s Laramie Basin floodplains. Disease, pesticide exposure, and drought eliminated the wild population by the early 1990s. Seven captive institutions now maintain the species, releasing thousands annually — though self-sustaining wild populations remain elusive.',
    category: 'animals',
    label: 'Amphibians',
    iucnStatus: 'EW',
    cover: null,
    coverPalette: { from: '#08041a', via: '#180c40', to: '#3a2070' },
    featured: false,
    createdAt: '2026-04-21T05:10:00.000Z',
    authorId: 'u_ceo',
    views: 290,
  },

  /* CR — Critically Endangered */
  {
    id: 'p30',
    slug: 'amur-leopard-critically-endangered',
    title: 'Amur Leopard',
    description: 'Fewer than 100 individuals survive in Russia\'s Far East — the rarest wild cat on Earth, adapted to brutal Siberian winters.',
    body: 'Panthera pardus orientalis grows a thick pale coat to survive Primorsky Krai winters and hunts roe and sika deer through snow. Poaching for its distinctive rosette-patterned fur collapsed the population to just 30 individuals by 2007. Conservation has recovered it to approximately 90–100 animals — still critically insufficient for long-term genetic viability.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'CR',
    cover: null,
    coverPalette: { from: '#1a0000', via: '#4a0808', to: '#8a1818' },
    featured: false,
    createdAt: '2026-04-21T05:00:00.000Z',
    authorId: 'u_ceo',
    views: 1240,
  },
  {
    id: 'p31',
    slug: 'vaquita-worlds-rarest-cetacean',
    title: 'Vaquita',
    description: 'Approximately 10 individuals remain in Mexico\'s Gulf of California — the world\'s most endangered marine mammal and smallest cetacean.',
    body: 'Phocoena sinus was not scientifically described until 1958. By 2018, fewer than 19 individuals were estimated to survive — caught as bycatch in illegal gillnets set for the equally endangered totoaba fish. Despite a gillnet ban and navy patrols, poaching continues. It is almost certainly functionally extinct.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'CR',
    cover: null,
    coverPalette: { from: '#0a0818', via: '#200c28', to: '#501030' },
    featured: false,
    createdAt: '2026-04-21T04:50:00.000Z',
    authorId: 'u_ceo',
    views: 980,
  },
  {
    id: 'p32',
    slug: 'javan-rhino-last-population',
    title: 'Javan Rhino',
    description: 'The rarest large mammal on Earth — ~74 individuals in a single national park in Java, with no captive population as a safety net.',
    body: 'Rhinoceros sondaicus once ranged from northeastern India through Southeast Asia. A single population now survives in Ujung Kulon National Park. There are no Javan rhinos in captivity. The park sits 50 km from Anak Krakatau volcano — a single eruption could eliminate the species entirely.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'CR',
    cover: null,
    coverPalette: { from: '#1a0400', via: '#4a1008', to: '#7a2010' },
    featured: false,
    createdAt: '2026-04-21T04:40:00.000Z',
    authorId: 'u_ceo',
    views: 870,
  },
  {
    id: 'p33',
    slug: 'sumatran-orangutan-cr',
    title: 'Sumatran Orangutan',
    description: 'Fewer than 14,000 survive in fragmented northern Sumatran forests — a cognitive peer to humans losing ground to palm oil expansion.',
    body: 'Pongo abelii shares 97% of its DNA with humans, demonstrating tool use, cultural transmission, and long-term planning. Palm oil expansion and illegal logging have destroyed over 80% of its lowland forest habitat since 1980. A female may have only three to four offspring in her 45-year lifespan — among the slowest reproductive rates of any land mammal.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'CR',
    cover: null,
    coverPalette: { from: '#1a0600', via: '#500c08', to: '#901808' },
    featured: false,
    createdAt: '2026-04-21T04:30:00.000Z',
    authorId: 'u_ceo',
    views: 1060,
  },
  {
    id: 'p34',
    slug: 'cross-river-gorilla-cr',
    title: 'Cross River Gorilla',
    description: 'Fewer than 300 individuals survive on the Nigeria–Cameroon border — the most critically threatened of all gorilla subspecies.',
    body: 'Gorilla gorilla diehli occupies highland forest split into at least 11 isolated subpopulations, some with fewer than 20 individuals. It is distinguished by extreme shyness — almost certainly a response to centuries of human hunting. Most of what science knows comes from camera traps and nest surveys, as direct observation is nearly impossible.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'CR',
    cover: null,
    coverPalette: { from: '#080e00', via: '#1a1800', to: '#402010' },
    featured: false,
    createdAt: '2026-04-21T04:20:00.000Z',
    authorId: 'u_ceo',
    views: 720,
  },

  /* EN — Endangered */
  {
    id: 'p35',
    slug: 'african-wild-dog-endangered',
    title: 'African Wild Dog',
    description: 'Africa\'s most efficient predator — 70–80% kill success rate — now fragmented into fewer than 39 isolated populations across the continent.',
    body: 'Lycaon pictus hunts in coordinated packs with a democratic decision-making process unique among canids — individuals sneeze to vote on when to hunt. Their painted coats and hyperactive social bonds define a species that once ranged across 39 countries and now survives in approximately 6,600 individuals, threatened by habitat fragmentation and canine distemper.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EN',
    cover: null,
    coverPalette: { from: '#1a0800', via: '#4a1c04', to: '#8a3c08' },
    featured: false,
    createdAt: '2026-04-21T04:10:00.000Z',
    authorId: 'u_ceo',
    views: 890,
  },
  {
    id: 'p36',
    slug: 'sumatran-tiger-en',
    title: 'Sumatran Tiger',
    description: 'Fewer than 400 remain — the last tiger subspecies of the Sunda Islands, clinging to existence in rapidly disappearing rainforest.',
    body: 'Panthera tigris sumatrae is the smallest surviving tiger subspecies, adapted to dense rainforests of Sumatra. Sumatra has lost 85% of its original forest cover since the 1900s, with accelerating conversion to palm oil and paper plantations pushing the tiger to its final fragments. Each individual is now precious; poaching for skins and bones remains a constant threat.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EN',
    cover: null,
    coverPalette: { from: '#1a0800', via: '#4a1800', to: '#903000' },
    featured: false,
    createdAt: '2026-04-21T04:00:00.000Z',
    authorId: 'u_ceo',
    views: 1120,
  },
  {
    id: 'p37',
    slug: 'blue-whale-en',
    title: 'Blue Whale',
    description: 'The largest animal to have ever lived on Earth — reduced from 300,000 to fewer than 25,000 by a century of industrial whaling.',
    body: 'Balaenoptera musculus produces calls reaching 188 decibels — louder than a jet engine — that travel thousands of kilometres through the ocean. Before industrial whaling, an estimated 300,000 blue whales swam the world\'s oceans. By 1966, when protection finally came, fewer than 1,000 may have remained. Recovery is painfully slow, hampered by ship strikes, noise pollution, and entanglement in fishing gear.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EN',
    cover: null,
    coverPalette: { from: '#020820', via: '#081848', to: '#103878' },
    featured: false,
    createdAt: '2026-04-21T03:50:00.000Z',
    authorId: 'u_ceo',
    views: 1450,
  },
  {
    id: 'p38',
    slug: 'galapagos-penguin-en',
    title: 'Galápagos Penguin',
    description: 'The only penguin found north of the equator — fewer than 1,800 individuals sustained by cold upwelling currents in tropical waters.',
    body: 'Spheniscus mendiculus exists because the Cromwell Current delivers cold, nutrient-rich water directly to the equatorial Galápagos Islands. El Niño events, which warm surface waters and collapse fish populations, can kill 75% of a breeding colony in a single year. Climate change is predicted to make such events more frequent and severe.',
    category: 'birds',
    label: 'Seabirds',
    iucnStatus: 'EN',
    cover: null,
    coverPalette: { from: '#020c18', via: '#041c38', to: '#084868' },
    featured: false,
    createdAt: '2026-04-21T03:40:00.000Z',
    authorId: 'u_ceo',
    views: 640,
  },
  {
    id: 'p39',
    slug: 'ethiopian-wolf-en',
    title: 'Ethiopian Wolf',
    description: 'The world\'s rarest canid — fewer than 500 surviving in Ethiopian highlands — a flame-coloured wolf that hunts mole-rats above 3,000 metres.',
    body: 'Canis simensis is Africa\'s most endangered carnivore, found only in the Afroalpine grasslands of Ethiopia. Rabies transmitted from village dogs can kill 70% of a pack within weeks. Fewer than 500 individuals survive across six isolated mountain ranges, making each subpopulation devastatingly vulnerable to a single disease outbreak.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'EN',
    cover: null,
    coverPalette: { from: '#1a0800', via: '#501004', to: '#9a2c08' },
    featured: false,
    createdAt: '2026-04-21T03:30:00.000Z',
    authorId: 'u_ceo',
    views: 510,
  },

  /* VU — Vulnerable */
  {
    id: 'p40',
    slug: 'polar-bear-vu',
    title: 'Polar Bear',
    description: 'The world\'s largest land carnivore, built entirely around sea ice — which is disappearing at 13% per decade due to climate change.',
    body: 'Ursus maritimus has evolved over 150,000 years into the definitive apex predator of the Arctic. Its entire ecology is organized around annual sea ice cycles. The IPCC projects Arctic summers will be ice-free by 2040. At current trends, the IUCN projects a greater than 30% population decline within three generations — approximately 45 years.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'VU',
    cover: null,
    coverPalette: { from: '#080c18', via: '#182848', to: '#406890' },
    featured: false,
    createdAt: '2026-04-21T03:20:00.000Z',
    authorId: 'u_ceo',
    views: 1380,
  },
  {
    id: 'p41',
    slug: 'great-white-shark-vu',
    title: 'Great White Shark',
    description: '450 million years of evolutionary refinement — yet precise global population counts remain unknown, a data gap of alarming conservation magnitude.',
    body: 'Carcharodon carcharias is the ocean\'s most perfectly realised apex predator, capable of detecting one part blood per million parts seawater. Great whites take 15 years to reach sexual maturity and produce only 2–14 pups per litter — making populations extremely slow to recover from fishing pressure. Estimates range from 2,000–3,500 mature individuals in the Atlantic and Pacific combined.',
    category: 'animals',
    label: 'Fish',
    iucnStatus: 'VU',
    cover: null,
    coverPalette: { from: '#08101a', via: '#142038', to: '#2a4060' },
    featured: false,
    createdAt: '2026-04-21T03:10:00.000Z',
    authorId: 'u_ceo',
    views: 1670,
  },
  {
    id: 'p42',
    slug: 'hippopotamus-vu',
    title: 'Hippopotamus',
    description: 'Africa\'s most dangerous large mammal — a semi-aquatic ecosystem engineer whose population has declined by up to 20% since 2016.',
    body: 'Hippopotamus amphibius spends up to 16 hours daily submerged to protect its hairless, sun-sensitive skin. Their natural secretion — often called "blood sweat" — is actually a natural sunscreen and antimicrobial fluid. Civil conflict, poaching for ivory-like canine teeth, and habitat loss have reduced populations to 115,000–130,000 individuals.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'VU',
    cover: null,
    coverPalette: { from: '#100c04', via: '#302818', to: '#605040' },
    featured: false,
    createdAt: '2026-04-21T03:00:00.000Z',
    authorId: 'u_ceo',
    views: 870,
  },
  {
    id: 'p43',
    slug: 'komodo-dragon-vu',
    title: 'Komodo Dragon',
    description: 'The largest living lizard — a venomous island predator confined to five Indonesian islands with a combined area smaller than Los Angeles.',
    body: 'Varanus komodoensis can reach 3 metres and 70 kg, hunting deer, pigs, and water buffalo with ambush tactics and venom that prevents blood clotting. Found only on Komodo, Rinca, Flores, Gili Motang, and Padar islands, the population is approximately 1,380 adults. Rising sea levels threaten to inundate its low-lying nesting beaches by 2050.',
    category: 'animals',
    label: 'Reptiles',
    iucnStatus: 'VU',
    cover: null,
    coverPalette: { from: '#0a1000', via: '#202c00', to: '#485010' },
    featured: false,
    createdAt: '2026-04-21T02:50:00.000Z',
    authorId: 'u_ceo',
    views: 760,
  },
  {
    id: 'p44',
    slug: 'leatherback-sea-turtle-vu',
    title: 'Leatherback Sea Turtle',
    description: 'The world\'s largest reptile — diving to 1,000 metres — sustained by jellyfish and fatally threatened by the plastic bags that mimic them.',
    body: 'Dermochelys coriacea is the only living sea turtle lacking a hard shell. It can regulate its body temperature in cold waters and dive deeper than any other reptile. Pacific leatherback populations have declined by 95% since 1980, driven by bycatch in longline fisheries, egg harvesting, and plastic ingestion. The Atlantic population has fared slightly better under enhanced beach protection.',
    category: 'animals',
    label: 'Reptiles',
    iucnStatus: 'VU',
    cover: null,
    coverPalette: { from: '#040c18', via: '#0c2030', to: '#204858' },
    featured: false,
    createdAt: '2026-04-21T02:40:00.000Z',
    authorId: 'u_ceo',
    views: 680,
  },

  /* NT — Near Threatened */
  {
    id: 'p45',
    slug: 'jaguar-near-threatened',
    title: 'Jaguar',
    description: 'The Americas\' only big cat — a keystone predator whose range has contracted by 51% since European colonisation.',
    body: 'Panthera onca is the largest cat in the Western Hemisphere, distinguished by its massive skull, compact body, and unique rosette patterns. Unlike other big cats, jaguars are powerful swimmers and hunt caimans and anacondas in river systems. An estimated 64,000 remain across a fragmented range from Mexico to Argentina, managed through transnational jaguar corridor initiatives.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'NT',
    cover: null,
    coverPalette: { from: '#141000', via: '#3a2c04', to: '#785c0c' },
    featured: false,
    createdAt: '2026-04-21T02:30:00.000Z',
    authorId: 'u_ceo',
    views: 1050,
  },
  {
    id: 'p46',
    slug: 'narwhal-unicorn-sea',
    title: 'Narwhal',
    description: 'The unicorn of the sea — an Arctic whale whose 3-metre spiral tusk contains 10 million nerve endings and functions as a sensory array.',
    body: 'Monodon monoceros navigates under sea ice for up to five months in Arctic winter darkness, diving to 1,500 metres to hunt Greenland halibut and Arctic cod. The tusk — found almost exclusively in males — is an elongated upper canine tooth, the only straight-spiral tusk in nature. An estimated 75,000–80,000 narwhals inhabit Canadian and Greenlandic waters.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'NT',
    cover: null,
    coverPalette: { from: '#040c18', via: '#0c2440', to: '#3060a8' },
    featured: false,
    createdAt: '2026-04-21T02:20:00.000Z',
    authorId: 'u_ceo',
    views: 780,
  },
  {
    id: 'p47',
    slug: 'maned-wolf-nt',
    title: 'Maned Wolf',
    description: 'South America\'s tallest canid — not a wolf, not a fox — a long-legged grassland predator with a haunting nocturnal howl.',
    body: 'Chrysocyon brachyurus represents a unique evolutionary lineage, the sole member of its genus. Its extraordinary long legs evolved to see over the tall grasses of the Brazilian Cerrado. Its diet is 50% plant matter — the wolf apple provides the majority of its calories, making it a critical seed disperser. Approximately 23,000 individuals remain in a biome losing 3% of its area annually to agriculture.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'NT',
    cover: null,
    coverPalette: { from: '#180a00', via: '#442010', to: '#885028' },
    featured: false,
    createdAt: '2026-04-21T02:10:00.000Z',
    authorId: 'u_ceo',
    views: 490,
  },
  {
    id: 'p48',
    slug: 'striped-hyena-nt',
    title: 'Striped Hyena',
    description: 'The most widespread hyena — a prehistoric survivor found from North Africa to India, prowling the same landscapes for 3.5 million years.',
    body: 'Hyaena hyaena is the only hyena species found outside sub-Saharan Africa, ranging across North Africa, the Middle East, and the Indian subcontinent. Unlike the spotted hyena, it is primarily a solitary scavenger capable of cracking bones that defeat almost any other predator. Fewer than 10,000 remain, declining due to persecution and road kills across its vast range.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'NT',
    cover: null,
    coverPalette: { from: '#141008', via: '#342c18', to: '#685a38' },
    featured: false,
    createdAt: '2026-04-21T02:00:00.000Z',
    authorId: 'u_ceo',
    views: 360,
  },

  /* LC — Least Concern */
  {
    id: 'p49',
    slug: 'red-fox-lc',
    title: 'Red Fox',
    description: 'The most geographically widespread wild carnivore on Earth — a supreme generalist that has colonised every continent except Antarctica.',
    body: 'Vulpes vulpes adapts from Arctic tundra to Saharan margins, from British suburbs to Himalayan altitudes above 4,500 metres. Thirty-seven million red foxes are estimated to inhabit Earth. Their intelligence — demonstrated in problem-solving, memory, and social learning — allows them to exploit virtually any food source. Urban fox populations in London now number in the tens of thousands.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'LC',
    cover: null,
    coverPalette: { from: '#1a0800', via: '#5a2408', to: '#c05010' },
    featured: false,
    createdAt: '2026-04-21T01:50:00.000Z',
    authorId: 'u_ceo',
    views: 420,
  },
  {
    id: 'p50',
    slug: 'common-raven-lc',
    title: 'Common Raven',
    description: 'The most cognitively complex non-human animal — a corvid that plans for the future, uses tools, and understands the minds of others.',
    body: 'Corvus corax demonstrates a theory of mind — understanding the perspective of others and anticipating their actions, a cognitive feat once thought exclusive to humans and great apes. Ravens plan for future events, cache food in locations known only to them, and retrieve it hours later. They play — engaging in aerial acrobatics and object manipulation with no obvious survival purpose.',
    category: 'birds',
    label: 'Corvids',
    iucnStatus: 'LC',
    cover: null,
    coverPalette: { from: '#080808', via: '#181818', to: '#303040' },
    featured: false,
    createdAt: '2026-04-21T01:40:00.000Z',
    authorId: 'u_ceo',
    views: 380,
  },
  {
    id: 'p51',
    slug: 'brown-bear-lc',
    title: 'Brown Bear',
    description: 'Apex predator of the northern hemisphere\'s forests — 200,000 individuals across three continents represent a rare conservation success.',
    body: 'Ursus arctos can consume 20,000 calories daily before hibernation, gaining up to 180 kg. The Kodiak population of Alaska, fed by extraordinary Pacific salmon runs, produces bears exceeding 600 kg — the largest land carnivores after polar bears. Brown bears are keystone species: their salmon-fishing behaviour transfers marine nutrients kilometres inland through uneaten carcasses.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'LC',
    cover: null,
    coverPalette: { from: '#140a00', via: '#3c2010', to: '#7a4a28' },
    featured: false,
    createdAt: '2026-04-21T01:30:00.000Z',
    authorId: 'u_ceo',
    views: 540,
  },
  {
    id: 'p52',
    slug: 'bottlenose-dolphin-lc',
    title: 'Bottlenose Dolphin',
    description: 'The most studied cetacean — a self-aware, culturally complex animal that gives each individual a unique name it uses for a lifetime.',
    body: 'Tursiops truncatus passes the mirror self-recognition test, a benchmark of self-awareness shared only with great apes, elephants, and magpies. Populations in Shark Bay, Australia use sponges as tools to protect their rostrums while foraging, a behaviour transmitted exclusively from mothers to daughters. Individual dolphins develop unique signature whistles that function as names — recognised and responded to by pod members for decades.',
    category: 'animals',
    label: 'Mammals',
    iucnStatus: 'LC',
    cover: null,
    coverPalette: { from: '#040c18', via: '#0c2440', to: '#286090' },
    featured: false,
    createdAt: '2026-04-21T01:20:00.000Z',
    authorId: 'u_ceo',
    views: 690,
  },

  /* DD — Data Deficient */
  {
    id: 'p53',
    slug: 'giant-squid-dd',
    title: 'Giant Squid',
    description: 'The largest invertebrate on Earth — up to 13 metres long — observed alive in its natural habitat for the first time only in 2004.',
    body: 'Architeuthis dux was long thought to be a sailor\'s myth. A live specimen was photographed in the deep Pacific in 2004 and video-recorded for the first time in 2012, at 630 metres depth. Their eyes, at 30 cm diameter, are the largest in the animal kingdom. Population size is genuinely unknown — sperm whale stomachs and commercial trawler nets provide our only data.',
    category: 'animals',
    label: 'Cephalopods',
    iucnStatus: 'DD',
    cover: null,
    coverPalette: { from: '#020410', via: '#080c28', to: '#142050' },
    featured: false,
    createdAt: '2026-04-21T01:10:00.000Z',
    authorId: 'u_ceo',
    views: 920,
  },
  {
    id: 'p54',
    slug: 'giant-freshwater-stingray-dd',
    title: 'Giant Freshwater Stingray',
    description: 'Possibly the world\'s largest freshwater fish by mass — up to 600 kg — and almost nothing is known about its actual population size.',
    body: 'Urogymnus polylepis inhabits river systems of Southeast Asia and Borneo. A specimen caught in Thailand\'s Mae Klong River in 2009 weighed approximately 600 kg. Its freshwater habitat is among the most threatened ecosystems on Earth — dams, gold mining, and overfishing are all major pressures. Scientific data on population size, distribution, and ecology remain extremely sparse.',
    category: 'animals',
    label: 'Fish',
    iucnStatus: 'DD',
    cover: null,
    coverPalette: { from: '#04080c', via: '#0c1820', to: '#203040' },
    featured: false,
    createdAt: '2026-04-21T01:00:00.000Z',
    authorId: 'u_ceo',
    views: 340,
  },

  /* ── Bird Species ──────────────────────────────────────── */
  {
    id: 'p55',
    slug: 'harpy-eagle-apex-raptor',
    title: 'Harpy Eagle',
    description: 'The most powerful eagle on Earth — talons the size of a grizzly bear\'s claws, hunting monkeys and sloths in the Amazon canopy.',
    body: 'Harpia harpyja is the largest and most powerful raptor in the Americas, with a wingspan reaching 2 metres and talons exceeding 13 cm. It hunts by gliding silently below the forest canopy, using its facial disc like a satellite dish to focus sound and pinpoint prey. A breeding pair requires up to 100 km² of undisturbed rainforest, making them acutely sensitive to deforestation.',
    category: 'birds',
    label: 'Raptors',
    cover: null,
    coverPalette: { from: '#080c14', via: '#182038', to: '#405070' },
    featured: false,
    createdAt: '2026-04-22T10:00:00.000Z',
    authorId: 'u_ceo',
    views: 1180,
  },
  {
    id: 'p56',
    slug: 'wandering-albatross',
    title: 'Wandering Albatross',
    description: 'The longest wingspan of any living bird at 3.5 metres — spending years aloft over the Southern Ocean without once touching land.',
    body: 'Diomedea exulans uses dynamic soaring — a technique that extracts energy from wind gradients above ocean waves — to travel over 120,000 km per year with almost no muscular effort. An albatross may fly 10 million km in its 50-year lifetime. Juveniles spend the first six years entirely at sea. Longline fishing hooks kill an estimated 100,000 albatrosses annually across all species.',
    category: 'birds',
    label: 'Seabirds',
    cover: null,
    coverPalette: { from: '#0a1018', via: '#203048', to: '#6080a8' },
    featured: false,
    createdAt: '2026-04-22T09:00:00.000Z',
    authorId: 'u_ceo',
    views: 840,
  },
  {
    id: 'p57',
    slug: 'greater-flamingo',
    title: 'Greater Flamingo',
    description: 'The most widespread flamingo — a social architect whose pink plumage comes entirely from the carotenoid pigments in its diet.',
    body: 'Phoenicopterus roseus filters up to 20 litres of water per day through specialised lamellae in its uniquely inverted bill. Their pink coloration is not genetic — flamingos raised without carotenoid-rich brine shrimp and algae are white. They stand on one leg not for balance but to conserve body heat, tucking the other against their warm body. Colonies can number over a million birds.',
    category: 'birds',
    label: 'Waders',
    cover: null,
    coverPalette: { from: '#180808', via: '#501828', to: '#c05070' },
    featured: false,
    createdAt: '2026-04-22T08:00:00.000Z',
    authorId: 'u_ceo',
    views: 970,
  },
  {
    id: 'p58',
    slug: 'shoebill-stork',
    title: 'Shoebill',
    description: 'A prehistoric-looking giant of Central African swamps — its 24-cm bill delivers one of the most powerful snaps in the avian world.',
    body: 'Balaeniceps rex stands up to 1.5 metres tall in the papyrus swamps of Uganda, Sudan, and the Congo Basin. It hunts lungfish, monitor lizards, and even juvenile crocodiles by standing motionless for hours, then striking with a bill powerful enough to decapitate its prey. Shoebills are notoriously still — some observers spend hours watching them without seeing a single movement.',
    category: 'birds',
    label: 'Waders',
    cover: null,
    coverPalette: { from: '#080c10', via: '#182838', to: '#385870' },
    featured: false,
    createdAt: '2026-04-22T07:00:00.000Z',
    authorId: 'u_ceo',
    views: 1320,
  },
  {
    id: 'p59',
    slug: 'snowy-owl',
    title: 'Snowy Owl',
    description: 'The Arctic\'s silent sentinel — the heaviest owl in North America, hunting lemmings beneath the midnight sun of the tundra.',
    body: 'Bubo scandiacus is the only white owl in the world, perfectly camouflaged for Arctic tundra and sea ice. Unlike most owls, snowy owls are diurnal — hunting in full Arctic daylight during summer. A single snowy owl can consume over 1,600 lemmings per year. When lemming populations crash, owls irrupt southward in remarkable numbers, appearing in cities and airports far outside their normal range.',
    category: 'birds',
    label: 'Owls',
    cover: null,
    coverPalette: { from: '#0c1018', via: '#283858', to: '#7090c0' },
    featured: false,
    createdAt: '2026-04-22T06:00:00.000Z',
    authorId: 'u_ceo',
    views: 760,
  },
  {
    id: 'p60',
    slug: 'scarlet-macaw',
    title: 'Scarlet Macaw',
    description: 'The most vivid bird of the Americas — a long-lived, highly intelligent parrot that mates for life and navigates vast tropical landscapes.',
    body: 'Ara macao is one of the largest parrots in the world, living up to 75 years and forming lifelong pair bonds. Their brilliant red, yellow, and blue plumage is produced by unique pigments called psittacofulvins, found only in parrots. Scarlet macaws can crack palm nuts that require 300 kg of pressure to open. Illegal pet trade and habitat loss have eliminated them from much of their historical range.',
    category: 'birds',
    label: 'Parrots',
    cover: null,
    coverPalette: { from: '#1a0400', via: '#601008', to: '#c82020' },
    featured: false,
    createdAt: '2026-04-22T05:00:00.000Z',
    authorId: 'u_ceo',
    views: 890,
  },
  {
    id: 'p61',
    slug: 'african-grey-parrot',
    title: 'African Grey Parrot',
    description: 'Widely considered the most intelligent bird on Earth — demonstrating abstract reasoning, counting, and zero-concept understanding.',
    body: 'Psittacus erithacus was the subject of over 30 years of research by Dr Irene Pepperberg, whose subject Alex demonstrated the ability to count, identify colours, shapes, and materials, and understood the concept of zero. Grey parrots in the wild rely on complex social knowledge to find food, using information passed between individuals. Wild populations have crashed 90% due to trapping for the pet trade.',
    category: 'birds',
    label: 'Parrots',
    cover: null,
    coverPalette: { from: '#101010', via: '#303030', to: '#686868' },
    featured: false,
    createdAt: '2026-04-22T04:00:00.000Z',
    authorId: 'u_ceo',
    views: 1040,
  },
  {
    id: 'p62',
    slug: 'andean-condor',
    title: 'Andean Condor',
    description: 'The largest flying bird by combined wingspan and weight — soaring on Andean thermals for hours without a single wingbeat.',
    body: 'Vultur gryphus has a wingspan of up to 3.3 metres and can soar over 200 km per day using updrafts along the Andes without flapping its wings. Condors are one of the longest-lived birds — individuals can reach 70 years. They are critical scavengers, removing carcasses that would otherwise spread disease across high-altitude ecosystems. A near-extinction in the late 20th century has been partially reversed through captive breeding.',
    category: 'birds',
    label: 'Raptors',
    cover: null,
    coverPalette: { from: '#0c0c0c', via: '#241424', to: '#483048' },
    featured: false,
    createdAt: '2026-04-22T03:00:00.000Z',
    authorId: 'u_ceo',
    views: 720,
  },
  {
    id: 'p63',
    slug: 'indian-peafowl',
    title: 'Indian Peafowl',
    description: 'Evolution\'s most extravagant display — a 2-metre iridescent train that is the product of millions of years of female choice.',
    body: 'Pavo cristatus produces its spectacular train — which can span 2.1 metres — entirely for mate attraction. The iridescent colours are structural, produced by light interference in microscopic crystal lattices within each feather barb, not by pigments. Research has shown that peahens choose males based on the number, symmetry, and iridescence of their eyespots. Peacocks can take four years to fully develop their train.',
    category: 'birds',
    label: 'Pheasants',
    cover: null,
    coverPalette: { from: '#04100a', via: '#0c2c1c', to: '#206040' },
    featured: false,
    createdAt: '2026-04-22T02:00:00.000Z',
    authorId: 'u_ceo',
    views: 810,
  },
  {
    id: 'p64',
    slug: 'peregrine-falcon',
    title: 'Peregrine Falcon',
    description: 'The fastest animal on Earth at 389 km/h in a stoop dive — and one of conservation\'s greatest comeback stories.',
    body: 'Falco peregrinus reaches 389 km/h in a hunting stoop — the fastest recorded speed of any animal on Earth. It was functionally extinct east of the Rockies by 1970, wiped out by DDT. Today it nests on skyscrapers from New York to Tokyo, its population fully recovered. The peregrine is found on every continent except Antarctica, making it the most widespread bird of prey on Earth.',
    category: 'birds',
    label: 'Falcons',
    cover: null,
    coverPalette: { from: '#0a0c10', via: '#182230', to: '#385870' },
    featured: false,
    createdAt: '2026-04-22T01:00:00.000Z',
    authorId: 'u_ceo',
    views: 1560,
  },
];

export const SEED_USERS = [
  {
    id: 'u_ceo',
    email: CEO_EMAIL,
    password: CEO_PASSWORD,
    firstName: 'Wildlife',
    lastName: 'CEO',
    country: 'KE',
    avatarId: 'lion',
    role: 'ceo',
    createdAt: '2026-04-19T00:00:00.000Z',
  },
];
