export const IUCN_CONFIG = {
  EX: {
    code: 'EX',
    label: 'Extinct',
    shortDesc: 'No known individuals remaining in the wild or captivity',
    longDesc: 'A taxon is Extinct when there is no reasonable doubt that the last individual has died. This includes species that have vanished from the planet entirely, with exhaustive surveys across their historic range failing to record any individual. Extinction is irreversible — once a species is lost, it is lost forever.',
    color: '#888888',
    textColor: '#cccccc',
    badgeBg: 'rgba(30,30,30,0.92)',
    glow: 'rgba(136,136,136,0.22)',
    rowAccent: '#555555',
  },
  EW: {
    code: 'EW',
    label: 'Extinct in the Wild',
    shortDesc: 'Survives only in captivity or outside its native range',
    longDesc: 'A taxon is Extinct in the Wild when it is known only to survive in cultivation, captivity, or as a naturalized population outside its native range. These species have vanished from their natural habitats but cling to existence through human-managed care — zoos, botanical gardens, and breeding programs become their last refuge.',
    color: '#9c5abc',
    textColor: '#d880f0',
    badgeBg: 'rgba(40,8,60,0.92)',
    glow: 'rgba(156,90,188,0.28)',
    rowAccent: '#7030a0',
  },
  CR: {
    code: 'CR',
    label: 'Critically Endangered',
    shortDesc: 'Facing an extremely high risk of extinction in the wild',
    longDesc: 'Critically Endangered species face an extremely high probability of extinction in the wild. Population sizes have crashed — often fewer than 250 mature individuals remain. Habitats are critically fragmented, and without immediate, targeted conservation action, these species will vanish within our lifetimes.',
    color: '#dc2020',
    textColor: '#ff7070',
    badgeBg: 'rgba(60,0,0,0.92)',
    glow: 'rgba(220,32,32,0.35)',
    rowAccent: '#cc0000',
  },
  EN: {
    code: 'EN',
    label: 'Endangered',
    shortDesc: 'Facing a very high risk of extinction in the wild',
    longDesc: 'Endangered species face a very high risk of extinction in the wild. Population declines, habitat loss, and ongoing threats place these animals and plants on a dangerous trajectory. Conservation efforts can still make a critical difference — but only if action is taken with urgency before populations collapse beyond recovery.',
    color: '#e06820',
    textColor: '#ffaa60',
    badgeBg: 'rgba(50,18,0,0.92)',
    glow: 'rgba(224,104,32,0.35)',
    rowAccent: '#cc5500',
  },
  VU: {
    code: 'VU',
    label: 'Vulnerable',
    shortDesc: 'Facing a high risk of becoming endangered in the wild',
    longDesc: 'Vulnerable species face a high risk of endangerment if the factors causing their decline continue to operate. These species are not yet at the brink, but habitat degradation, overexploitation, and climate change are pushing them in that direction. Proactive conservation now can prevent a slide toward endangered status.',
    color: '#d4a800',
    textColor: '#ffe060',
    badgeBg: 'rgba(40,30,0,0.92)',
    glow: 'rgba(212,168,0,0.35)',
    rowAccent: '#ccaa00',
  },
  NT: {
    code: 'NT',
    label: 'Near Threatened',
    shortDesc: 'Close to qualifying for or likely to qualify as threatened',
    longDesc: 'Near Threatened species are close to qualifying as Vulnerable or are likely to qualify in the near future. They do not currently meet the thresholds for a threatened category, but their populations are under pressure and warrant close monitoring. Without continued vigilance, these species could quickly move into threatened status.',
    color: '#90c020',
    textColor: '#c8e860',
    badgeBg: 'rgba(16,28,0,0.92)',
    glow: 'rgba(144,192,32,0.28)',
    rowAccent: '#80aa10',
  },
  LC: {
    code: 'LC',
    label: 'Least Concern',
    shortDesc: 'Widespread and abundant, not currently facing significant threats',
    longDesc: 'Least Concern species are widespread, abundant, and do not currently qualify for a more threatened category. They have been evaluated against the IUCN criteria and found to be at low risk. However, Least Concern is not a guarantee of safety — continued monitoring ensures that any emerging threats are caught early.',
    color: '#28a028',
    textColor: '#70e870',
    badgeBg: 'rgba(0,28,0,0.92)',
    glow: 'rgba(40,160,40,0.28)',
    rowAccent: '#008000',
  },
  DD: {
    code: 'DD',
    label: 'Data Deficient',
    shortDesc: 'Inadequate information to assess risk of extinction',
    longDesc: 'Data Deficient species lack adequate information to make a direct or indirect assessment of their risk of extinction. Their true conservation status remains uncertain — they may be threatened, or they may be relatively secure. More research, field surveys, and data collection are urgently needed to reveal their situation.',
    color: '#5858a0',
    textColor: '#9898d0',
    badgeBg: 'rgba(12,12,40,0.92)',
    glow: 'rgba(88,88,160,0.28)',
    rowAccent: '#404080',
  },
};

export const IUCN_ORDER = ['EX', 'EW', 'CR', 'EN', 'VU', 'NT', 'LC', 'DD'];
